services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE=${DATABASE}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./app:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'  # Port for Nginx Proxy Manager UI
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./app/selfsigned.crt:/etc/nginx/certs/selfsigned.crt:ro
      - ./app/selfsigned.key:/etc/nginx/certs/selfsigned.key:ro

volumes:
  mongo-data: