services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE=${DATABASE}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app
    depends_on:
      - mongo
    networks:
      - frontend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - frontend

  nginx:
    image: nginx:latest
    volumes:
      - .:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - frontend

  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    depends_on:
      - db
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - frontend

  db:
    image: "mariadb:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - frontend

volumes:
  mongo-data:
  data:
  letsencrypt:
  mysql:

networks:
  frontend: